source:
  type: dbt
  serviceName: clickhouse_svc_name
  sourceConfig:
    config:
      type: DBT
      dbtConfigSource:
        dbtConfigType: local
        dbtManifestFilePath: /Users/quachtuankhoi/Data_Warehouse_Project/manifest.json
        dbtCatalogFilePath: /Users/quachtuankhoi/Data_Warehouse_Project/catalog.json
        # dbtRunResultsFilePath: path/to/run_results.json
      dbtUpdateDescriptions: true
      dbtUpdateOwners: true
      includeTags: true
      dbtClassificationName: dbtTags
      # databaseFilterPattern:
      #   includes:
      #     - .*db.*
      #   excludes:
      #     - .*demo.*
      # schemaFilterPattern:
      #   includes:
      #     - .*schema.*
      #   excludes:
      #     - .*demo.*
      # tableFilterPattern:
      #   includes:
      #     - .*table.*
      #   excludes:
      #     - .*demo.*
sink:
  type: metadata-rest
  config: {}
workflowConfig:
  loggerLevel: INFO  # DEBUG, INFO, WARNING or ERROR
  openMetadataServerConfig:
    hostPort: "http://localhost:8585/api"
    authProvider: openmetadata
    securityConfig:
      jwtToken: "eyJraWQiOiJHYjM4OWEtOWY3Ni1nZGpzLWE5MmotMDI0MmJrOTQzNTYiLCJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJvcGVuLW1ldGFkYXRhLm9yZyIsInN1YiI6ImluZ2VzdGlvbi1ib3QiLCJyb2xlcyI6WyJJbmdlc3Rpb25Cb3RSb2xlIl0sImVtYWlsIjoiaW5nZXN0aW9uLWJvdEBvcGVuLW1ldGFkYXRhLm9yZyIsImlzQm90Ijp0cnVlLCJ0b2tlblR5cGUiOiJCT1QiLCJ1c2VybmFtZSI6ImluZ2VzdGlvbi1ib3QiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJpbmdlc3Rpb24tYm90IiwiaWF0IjoxNzY3MjYzNTg2LCJleHAiOm51bGx9.12Mr8stZUFDG05P_VcUt03vtGS_z-u5aJsdNI_Zy9QdR_OP1wH1CZDHu-BukQM9lB6Uee_U3hVuR6gHAGg5aUlBFjws_1UTgL546L9c-6BYuNA7zY6e0AZ1dQORPuFto-8bduaw01UFOfjCeVyxB6tbkVOQeeU3AB5UHQEqThDUVnHQXyghXjFikqyRKmycC2836rd3pb8XrjoguDGVJIwY2Rock546EDdS0mUVZgN8Le1WIqgEhNH8F4C5m8BSmR2HQZWen-Sk_xgXcaxh2qLfg7J2vW62i-5mjnmChOei8MT7HL5Uy7CU0NdGW4sMPBUnAbDOnSAAHDGtVp3i1Hg"
    ## Store the service Connection information
    storeServiceConnection: true  # false
    ## Secrets Manager Configuration
    # secretsManagerProvider: aws, azure or noop
    # secretsManagerLoader: airflow or env
    ## If SSL, fill the following
    # verifySSL: validate  # or ignore
    # sslConfig:
    #   caCertificate: /local/path/to/certificate
# ingestionPipelineFQN: <service name>.<ingestion name> ## e.g., "my_redshift.metadata"
