# x-airflow-common:
#   &airflow-common
#   build:
#     context: .
#     dockerfile: docker/Dockerfile.airflow
#   image: ${AIRFLOW_IMAGE_NAME:-apache/airflow:3.1.3}
#   env_file:
#     - .env
#   environment:
#     &airflow-common-env
#     AIRFLOW__CORE__EXECUTOR: LocalExecutor
#     AIRFLOW__CORE__AUTH_MANAGER: airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager
#     AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${AIRFLOW_POSTGRES_USER}:${AIRFLOW_POSTGRES_PASSWORD}@postgres-backend-db:5432/${AIRFLOW_POSTGRES_DB}
#     AIRFLOW__CORE__FERNET_KEY: ''
#     AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
#     AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
#     AIRFLOW__CORE__EXECUTION_API_SERVER_URL: 'http://airflow-apiserver:8080/execution/'
#     AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK: 'true'
#     AIRFLOW_CONFIG: '/opt/airflow/config/airflow.cfg'
#   volumes:
#     - ./airflow/dags:/opt/airflow/dags
#     - ./airflow/logs:/opt/airflow/logs
#     - ./airflow/config:/opt/airflow/config
#     - ./airflow/plugins:/opt/airflow/plugins
#   user: "${AIRFLOW_UID:-50000}:0"
#   depends_on:
#     &airflow-common-depends-on
#     postgres-backend-db:
#       condition: service_healthy

services:
  postgres:
    container_name: postgres
    image: postgres:17
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_CLICKHOUSE_USER: ${POSTGRES_CLICKHOUSE_USER}
      POSTGRES_CLICKHOUSE_PASSWORD: ${POSTGRES_CLICKHOUSE_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./data_platform_config/clickhouse/integration/postgres/init/01_update_hba_file.sh:/docker-entrypoint-initdb.d/02_update_hba_file.sh:ro
      - ./data_source/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 10s
      timeout: 8s
      retries: 5

  clickhouse-01:
    image: "clickhouse/clickhouse-server:25.11"
    user: "101:101"
    container_name: clickhouse-01
    hostname: clickhouse-01
    volumes:
      - ./data_platform_config/clickhouse/fs/volumes/clickhouse-01/etc/clickhouse-server/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ./data_platform_config/clickhouse/fs/volumes/clickhouse-01/etc/clickhouse-server/users.d/users.xml:/etc/clickhouse-server/users.d/users.xml
      - ./ddl_script:/docker-entrypoint-initdb.d/
    ports:
      - 8123:8123
      - 9000:9000
    depends_on:
      - clickhouse-keeper-01
      - clickhouse-keeper-02
      - clickhouse-keeper-03

  clickhouse-02:
    image: "clickhouse/clickhouse-server:25.11"
    user: "101:101"
    container_name: clickhouse-02
    hostname: clickhouse-02
    volumes:
      - ./data_platform_config/clickhouse/fs/volumes/clickhouse-02/etc/clickhouse-server/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ./data_platform_config/clickhouse/fs/volumes/clickhouse-02/etc/clickhouse-server/users.d/users.xml:/etc/clickhouse-server/users.d/users.xml
    ports:
      - 8124:8123
      - 9001:9000
    depends_on:
      - clickhouse-keeper-01
      - clickhouse-keeper-02
      - clickhouse-keeper-03

  clickhouse-03:
    image: "clickhouse/clickhouse-server:25.11"
    user: "101:101"
    container_name: clickhouse-03
    hostname: clickhouse-03
    volumes:
      - ./data_platform_config/clickhouse/fs/volumes/clickhouse-03/etc/clickhouse-server/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ./data_platform_config/clickhouse/fs/volumes/clickhouse-03/etc/clickhouse-server/users.d/users.xml:/etc/clickhouse-server/users.d/users.xml
    ports:
      - 8125:8123
      - 9002:9000
    depends_on:
      - clickhouse-keeper-01
      - clickhouse-keeper-02
      - clickhouse-keeper-03

  clickhouse-04:
    image: "clickhouse/clickhouse-server:25.11"
    user: "101:101"
    container_name: clickhouse-04
    hostname: clickhouse-04
    volumes:
      - ./data_platform_config/clickhouse/fs/volumes/clickhouse-04/etc/clickhouse-server/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ./data_platform_config/clickhouse/fs/volumes/clickhouse-04/etc/clickhouse-server/users.d/users.xml:/etc/clickhouse-server/users.d/users.xml
    ports:
      - 8126:8123
      - 9003:9000
    depends_on:
      - clickhouse-keeper-01
      - clickhouse-keeper-02
      - clickhouse-keeper-03

  clickhouse-keeper-01:
    image: "clickhouse/clickhouse-keeper:25.11"
    user: "101:101"
    container_name: clickhouse-keeper-01
    hostname: clickhouse-keeper-01
    volumes:
      - ./data_platform_config/clickhouse/fs/volumes/clickhouse-keeper-01/etc/clickhouse-keeper/keeper_config.xml:/etc/clickhouse-keeper/keeper_config.xml
    ports:
      - 9181:9181

  clickhouse-keeper-02:
    image: "clickhouse/clickhouse-keeper:25.11"
    user: "101:101"
    container_name: clickhouse-keeper-02
    hostname: clickhouse-keeper-02
    volumes:
      - ./data_platform_config/clickhouse/fs/volumes/clickhouse-keeper-02/etc/clickhouse-keeper/keeper_config.xml:/etc/clickhouse-keeper/keeper_config.xml
    ports:
      - 9182:9181

  clickhouse-keeper-03:
    image: "clickhouse/clickhouse-keeper:25.11"
    user: "101:101"
    container_name: clickhouse-keeper-03
    hostname: clickhouse-keeper-03
    volumes:
      - ./data_platform_config/clickhouse/fs/volumes/clickhouse-keeper-03/etc/clickhouse-keeper/keeper_config.xml:/etc/clickhouse-keeper/keeper_config.xml
    ports:
      - 9183:9181

#   postgres-backend-db:
#     image: postgres:16
#     environment:
#       POSTGRES_USER: ${POSTGRES_BE_DB_USER}
#       POSTGRES_PASSWORD: ${POSTGRES_BE_DB_PASSWORD}
#       POSTGRES_DB: ${POSTGRES_BE_DB_DB}
#     volumes:
#       - postgres_backend_db-volume:/var/lib/postgresql/data
#       - ./data_platform_config/postgres_backend_db/integration/01_create_databases.sql:/docker-entrypoint-initdb.d/01_create_databases.sql:ro
#     ports:
#       - ${POSTGRES_BE_DB_PORT}:5432
#     healthcheck:
#       test: ["CMD", "pg_isready", "-U", "${POSTGRES_BE_DB_USER}"]
#       interval: 10s
#       retries: 5
#       start_period: 5s
#     restart: always

#   airflow-apiserver:
#     <<: *airflow-common
#     command: api-server
#     ports:
#       - 8080:8080
#     healthcheck:
#       test: ["CMD", "curl", "--fail", "http://localhost:8080/api/v2/version"]
#       interval: 30s
#       timeout: 10s
#       retries: 5
#       start_period: 30s
#     restart: always
#     depends_on:
#       <<: *airflow-common-depends-on
#       airflow-init:
#         condition: service_completed_successfully

#   airflow-scheduler:
#     <<: *airflow-common
#     command: scheduler
#     healthcheck:
#       test: ["CMD", "curl", "--fail", "http://localhost:8974/health"]
#       interval: 30s
#       timeout: 10s
#       retries: 5
#       start_period: 30s
#     restart: always
#     depends_on:
#       <<: *airflow-common-depends-on
#       airflow-init:
#         condition: service_completed_successfully

#   airflow-dag-processor:
#     <<: *airflow-common
#     command: dag-processor
#     healthcheck:
#       test: ["CMD-SHELL", 'airflow jobs check --job-type DagProcessorJob --hostname "$${HOSTNAME}"']
#       interval: 30s
#       timeout: 10s
#       retries: 5
#       start_period: 30s
#     restart: always
#     depends_on:
#       <<: *airflow-common-depends-on
#       airflow-init:
#         condition: service_completed_successfully

#   airflow-init:
#     <<: *airflow-common
#     entrypoint: /bin/bash
#     command:
#       - -c
#       - |
#         # Set AIRFLOW_UID nếu chưa có
#         if [[ -z "${AIRFLOW_UID}" ]]; then
#           export AIRFLOW_UID=$$(id -u)
#         fi

#         # Tạo thư mục cần thiết
#         mkdir -p /opt/airflow/{logs,dags,plugins,config}

#         # Khởi tạo config nếu chưa có
#         /entrypoint airflow config list >/dev/null

#         # Set quyền sở hữu thư mục
#         chown -R "${AIRFLOW_UID}:0" /opt/airflow/
#         chown -R "${AIRFLOW_UID}:0" /opt/airflow/{logs,dags,plugins,config}
#     environment:
#       <<: *airflow-common-env
#       _AIRFLOW_DB_MIGRATE: 'true'
#       _AIRFLOW_WWW_USER_CREATE: 'true'
#       _AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME:-airflow}
#       _AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD:-airflow}
#       _PIP_ADDITIONAL_REQUIREMENTS: ''
#     user: "0:0"

# volumes:
#   postgres_backend_db-volume: